version: 2
jobs:
  build:
    working_directory: ~/tourbot
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python src/main.py
