version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install pipenv
      - run: pipenv install -r requirements.txt
      - run:
          command: pipenv run python src/main.py test
          no_output_timeout: 20s
